<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="3" name="pytest" skips="0" tests="5" time="0.193"><testcase classname="pytest" file="pytest.py" line="12" name="test_answer" time="0.006999969482421875"><failure message="assert 4 == 5
 +  where 4 = inc(3)">def test_answer():
&gt;       assert inc(3) == 5
E       assert 4 == 5
E        +  where 4 = inc(3)

pytest.py:14: AssertionError</failure></testcase><testcase classname="pytest" file="pytest.py" line="15" name="test_wcf" time="0.004000186920166016"><failure message="assert 4 &gt; 5
 +  where 4 = inc(3)">def test_wcf():
&gt;       assert inc(3) &gt; 5
E       assert 4 &gt; 5
E        +  where 4 = inc(3)

pytest.py:17: AssertionError</failure></testcase><testcase classname="pytest" file="pytest.py" line="18" name="test_hy" time="0.0019998550415039062"></testcase><testcase classname="pytest.TestClass" file="pytest.py" line="22" name="test_one" time="0.0019998550415039062"></testcase><testcase classname="pytest.TestClass" file="pytest.py" line="25" name="test_two" time="0.003000020980834961"><failure message="AssertionError: assert False
 +  where False = hasattr(&apos;hello&apos;, &apos;name&apos;)">self = &lt;APITest.pytest.TestClass object at 0x0000000003BA9E10&gt;

    def test_two(self):
        x = &quot;hello&quot;
&gt;       assert hasattr(x,&quot;name&quot;)
E       AssertionError: assert False
E        +  where False = hasattr(&apos;hello&apos;, &apos;name&apos;)

pytest.py:28: AssertionError</failure></testcase></testsuite>